from __future__ import annotations

import json
import logging
import sys
from textwrap import dedent

from agent import CineResearchAgent
from models import MovieResearch
from tools import save_report_tool


def configure_logging() -> None:
    """Configure human-readable application logging."""

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
        datefmt="%H:%M:%S",
    )


def print_banner() -> None:
    """Print the CineResearch CLI banner."""

    print(
        dedent(
            """
            ╔══════════════════════════════════════════════════╗
            ║                 CineResearch                    ║
            ║          AI Movie Research Agent                ║
            ╚══════════════════════════════════════════════════╝
            """
        )
    )


def movie_research_to_markdown(
    research: MovieResearch,
) -> str:
    """Render validated MovieResearch data as Markdown."""

    cast = "\n".join(
        f"- {actor}"
        for actor in research.cast
    ) or "- No verified cast information found."

    genres = ", ".join(
        research.genres
    ) or "Not available"

    awards = "\n".join(
        f"- {award}"
        for award in research.awards
    ) or "- No verified major awards found."

    similar_movies = "\n".join(
        f"- {movie}"
        for movie in research.similar_movies
    ) or "- No verified recommendations found."

    sources = "\n".join(
        f"- {source}"
        for source in research.sources
    ) or "- No sources returned."

    tools_used = ", ".join(
        research.tools_used
    ) or "None"

    return f"""# {research.title}

## Overview

| Field | Value |
|---|---|
| Title | {research.title} |
| Release Year | {research.year} |
| Director | {research.director} |
| Genres | {genres} |

## Synopsis

{research.synopsis}

## Cast

{cast}

## Critical Reception

{research.critical_reception}

## Awards

{awards}

## Similar Movies

{similar_movies}

## Research Metadata

**Tools used:** {tools_used}

### Sources

{sources}

---

*Generated by CineResearch.*
"""


def print_structured_report(
    research: MovieResearch,
) -> None:
    """Print the validated Pydantic model as readable JSON."""

    print("\n" + "=" * 72)
    print("STRUCTURED MOVIE RESEARCH")
    print("=" * 72)

    print(
        json.dumps(
            research.model_dump(),
            indent=2,
            ensure_ascii=False,
        )
    )

    print("=" * 72)


def main() -> int:
    """Run the CineResearch command-line application."""

    configure_logging()
    print_banner()

    try:
        query = input(
            "What movie would you like me to research?\n> "
        ).strip()

        if not query:
            print("A research query is required.")
            return 1

        print(
            "\n[agent] Starting autonomous movie research...\n"
        )

        agent = CineResearchAgent()

        research, tools_used = agent.research(query)

        print(
            "\n[agent] Research complete."
        )

        print(
            "[agent] Tools used: "
            + (
                ", ".join(tools_used)
                if tools_used
                else "none"
            )
        )

        print_structured_report(research)

        markdown_report = movie_research_to_markdown(
            research
        )

        save_result = save_report_tool.invoke(
            {
                "title": research.title,
                "markdown_content": markdown_report,
            }
        )

        print(
            f"\n[persistence] {save_result}\n"
        )

        return 0

    except KeyboardInterrupt:
        print(
            "\n\nResearch cancelled by user."
        )
        return 130

    except ValueError as exc:
        print(
            f"\nConfiguration/input error: {exc}"
        )
        return 2

    except Exception as exc:
        logging.exception(
            "Fatal application error."
        )

        print(
            f"\nCineResearch failed: {exc}"
        )

        return 1


if __name__ == "__main__":
    sys.exit(main())